# sudo service docker start
version: "3.1"
services:
  db:
    image: postgres:latest
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  api:
    image: mpetrus/task-management-nestjs:latest
    depends_on:
      - db
    environment:
      NODE_ENV: production
      POSTGRES_HOST: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
  app:
    image: mpetrus/task-management-react:latest
    depends_on:
      - api
    volumes:
      - ./dist:./build
    environment:
      NODE_ENV: production
      API_HOST: api
