# sudo service docker start
version: "3.1"

services:
  app:
    image: mpetrus/task-management-react:latest
    ports:
      - ${APP_PORT}:3000
    environment:
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
